bp=input("Enter BP :- ")
da=input("Enter DA :- ")
hra=input("Enter HRA :- ")
loan=input("Enter loan :- ")
lic=input("Enter lic :- ")
gross_sal=int(bp)+int(da)+int(hra)
deduction=int(loan)+int(lic)
netsal=gross_sal-deduction
fo=open("salary.txt","w")
fo.write(bp+"\n"+da+"\n"+hra+"\n"+loan+"\n"+lic+"\n"+str(gross_sal)+"\n"+str(deduction)+"\n"+str(netsal))
fo.close()
fo=open("salary.txt","r")
print(fo.read())
fo.close()